# Generated by Django 6.1.1 on 2026-09-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('image_url', models.CharField(blank=True, default='', max_length=1000)),
                ('image_credit', models.CharField(blank=True, default='', max_length=500)),
                ('image_source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedDestination',
            fields=[
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='saved_entry', serialize=False, to='destinations.destination')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['category'], name='destination_categor_7c9900_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['location'], name='destination_locatio_771bdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together={('name', 'location')},
        ),
    ]
